Document: gulden
Title: Debian gulden Manual
Author: <insert document author here>
Abstract: This manual describes what gulden is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gulden/gulden.sgml.gz

Format: postscript
Files: /usr/share/doc/gulden/gulden.ps.gz

Format: text
Files: /usr/share/doc/gulden/gulden.text.gz

Format: HTML
Index: /usr/share/doc/gulden/html/index.html
Files: /usr/share/doc/gulden/html/*.html
